        case GC::CHARACTER_ADD: info = { sizeof(TPacketGCCharacterAddBeavium), false }; return true;
        case GC::CHARACTER_DEL: info = { sizeof(TPacketGCCharacterDelBeavium), false }; return true;
        case GC::CHARACTER_MOVE: info = { sizeof(TPacketGCCharacterMoveBeavium), false }; return true;
        case GC::CHAT: info = { sizeof(TPacketGCChatBeavium), true }; return true;
        case 0x05: info = { 3, true }; return true; // HEADER_GC_SYNC_POSITION
        case 0x06: info = { 10, false }; return true; // HEADER_GC_LOGIN_SUCCESS3
        case 0x07: info = { 91, false }; return true; // HEADER_GC_LOGIN_FAILURE
        case GC::CHAR_CREATE_SUCCESS: info = { sizeof(TPacketGCCharCreateSuccessBeavium), false }; return true;
        case GC::CHAR_CREATE_FAILURE: info = { sizeof(TPacketGCCharCreateFailureBeavium), false }; return true;
        case GC::CHAR_DELETE_SUCCESS: info = { sizeof(TPacketGCCharDeleteSuccessBeavium), false }; return true;
        case GC::CHAR_DELETE_WRONG_PIN: info = { sizeof(TPacketGCCharDeleteWrongPinBeavium), false }; return true;
        case GC::ATTACK: info = { sizeof(TPacketGCAttackBeavium), false }; return true;
        case 0x0D: info = { 3073, false }; return true; // HEADER_GC_STUN
        case GC::DEAD: info = { sizeof(TPacketGCDeadBeavium), false }; return true;
        case 0x0F: info = { 6, true }; return true; // HEADER_GC_MAIN_CHARACTER
        case GC::CHARACTER_UPDATE: info = { sizeof(TPacketGCItemSetBeavium), false }; return true;
        case 0x11: info = { 4, false }; return true; // HEADER_GC_ITEM_USE
        case GC::ITEM_UPDATE: info = { sizeof(TPacketGCItemUpdateBeavium), false }; return true;
        case GC::ITEM_GROUND_ADD: info = { sizeof(TPacketGCItemGroundAddBeavium), false }; return true;
        case 0x15: info = { 268, false }; return true; // HEADER_GC_QUICKSLOT_ADD
        case 0x16: info = { 26, false }; return true; // HEADER_GC_QUICKSLOT_DEL
        case 0x17: info = { 5, false }; return true; // HEADER_GC_QUICKSLOT_SWAP
        case 0x18: info = { 4, false }; return true; // HEADER_GC_ITEM_OWNERSHIP
        case 0x19: info = { 2, false }; return true; // HEADER_GC_WHISPER
        case 0x1A: info = { 3, false }; return true; // HEADER_GC_MOTION
        case 0x1B: info = { 38, false }; return true; // HEADER_GC_SHOP
        case 0x1C: info = { 465, false }; return true; // HEADER_GC_SHOP_SIGN
        case 0x1D: info = { 37, true }; return true; // HEADER_GC_DUEL_START
        case 0x1E: info = { 11, false }; return true; // HEADER_GC_PVP
        case 0x1F: info = { 4, true }; return true; // HEADER_GC_EXCHANGE
        case 0x20: info = { 70, false }; return true; // HEADER_GC_CHARACTER_POINTS
        case 0x21: info = { 3, true }; return true; // HEADER_GC_CHARACTER_POINT_CHANGE
        case 0x22: info = { 277, false }; return true; // HEADER_GC_EXCHANGE
        case 0x23: info = { 277, false }; return true; // HEADER_GC_RANKING_DATA
        case 0x24: info = { 6, false }; return true; // HEADER_GC_HANDSHAKE
        case GC::SCRIPT: info = { sizeof(TPacketGCScriptBeavium), true }; return true;
        case 0x26: info = { 6, true }; return true; // HEADER_GC_QUEST_BUTTON
        case 0x27: info = { 4, true }; return true; // HEADER_GC_SHOP
        case 0x28: info = { 4, true }; return true; // HEADER_GC_CREATE_FLYING
        case 0x29: info = { 2, false }; return true; // HEADER_GC_CHANGE_CHANNEL
        case 0x2A: info = { 18, false }; return true; // HEADER_GC_UNKNOWN_2A
        case 0x2B: info = { 9, false }; return true; // HEADER_GC_CHARACTER_STATE
        case 0x2C: info = { 1, false }; return true; // HEADER_GC_PING
        case 0x2D: info = { 32, false }; return true; // HEADER_GC_ADD_FLY_TARGETING
        case 0x2E: info = { 17, false }; return true; // HEADER_GC_SKILL_LEVEL
        case 0x2F: info = { 10, false }; return true; // HEADER_GC_SKILL_COOLTIME_END
        case 0x30: info = { 17, false }; return true; // HEADER_GC_MESSENGER
        case 0x31: info = { 2, false }; return true; // HEADER_GC_GUILD
        case 0x32: info = { 4, true }; return true; // HEADER_GC_PARTY_INVITE
        case 0x33: info = { 4, true }; return true; // HEADER_GC_PARTY_ADD
        case 0x34: info = { 3571, false }; return true; // HEADER_GC_PARTY_UPDATE
        case 0x35: info = { 5, false }; return true; // HEADER_GC_PARTY_REMOVE
        case 0x36: info = { 45, false }; return true; // HEADER_GC_QUEST_INFO
        case 0x37: info = { 29, false }; return true; // HEADER_GC_REQUEST_MAKE_GUILD
        case 0x38: info = { 6, false }; return true; // HEADER_GC_PARTY_PARAMETER
        case 0x39: info = { 106, false }; return true; // HEADER_GC_QUEST_INFO
        case 0x3A: info = { 1, false }; return true; // HEADER_GC_SAFEBOX_DEL
        case 0x3B: info = { 2, false }; return true; // HEADER_GC_SAFEBOX_WRONG_PASSWORD
        case 0x3C: info = { 5, false }; return true; // HEADER_GC_SAFEBOX_SIZE
        case 0x3D: info = { 281, false }; return true; // HEADER_GC_FISHING
        case 0x3E: info = { 2, false }; return true; // HEADER_GC_DUNGEON
        case 0x3F: info = { 1, false }; return true; // HEADER_GC_TIME
        case 0x40: info = { 2, false }; return true; // HEADER_GC_WALK_MODE
        case 0x41: info = { 8, false }; return true; // HEADER_GC_CHANGE_SKILL_GROUP
        case 0x42: info = { 2, false }; return true; // HEADER_GC_REFINE_INFORMATION
        case 0x43: info = { 9, false }; return true; // HEADER_GC_SPECIAL_EFFECT
        case 0x44: info = { 9, false }; return true; // HEADER_GC_NPC_POSITION
        case 0x45: info = { 136, false }; return true; // HEADER_GC_UNKNOWN_45
        case 0x49: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_49
        case 0x4D: info = { 23, false }; return true; // HEADER_GC_EFFECT_ATTACH
        case 0x4E: info = { 38, false }; return true; // HEADER_GC_UNKNOWN_4E
        case 0x4F: info = { 4, true }; return true; // HEADER_GC_UNKNOWN_4F
        case 0x50: info = { 6, false }; return true; // HEADER_GC_VIEW_EQUIP
        case 0x51: info = { 2, false }; return true; // HEADER_GC_UNKNOWN_51
        case 0x52: info = { 6, false }; return true; // HEADER_GC_TARGET_LOCK
        case 0x53: info = { 5, true }; return true; // HEADER_GC_MINIMAP_WAYPOINTS
        case 0x55: info = { 69, false }; return true; // HEADER_GC_UNKNOWN_55
        case 0x56: info = { 2, false }; return true; // HEADER_GC_UNKNOWN_56
        case 0x57: info = { 2, false }; return true; // HEADER_GC_AFFECT_ADD
        case 0x58: info = { 17, false }; return true; // HEADER_GC_AFFECT_REMOVE
        case 0x59: info = { 5, false }; return true; // HEADER_GC_UNKNOWN_59
        case 0x5A: info = { 47, false }; return true; // HEADER_GC_MINIMAP_NPC_MARK
        case 0x5B: info = { 31, false }; return true; // HEADER_GC_EXTENDED_POINT_CHANGE
        case 0x5C: info = { 11, false }; return true; // HEADER_GC_SPECIAL_SKILL_UPDATE
        case 0x5D: info = { 281, false }; return true; // HEADER_GC_UNKNOWN_5D
        case 0x5E: info = { 2, false }; return true; // HEADER_GC_UNKNOWN_5E
        case 0x5F: info = { 3, true }; return true; // HEADER_GC_OFFLINE_SHOP_DATA
        case 0x60: info = { 35, false }; return true; // HEADER_GC_UNKNOWN_60
        case 0x61: info = { 2, false }; return true; // HEADER_GC_UNKNOWN_61
        case 0x63: info = { 10, false }; return true; // HEADER_GC_UNKNOWN_63
        case 0x64: info = { 14, false }; return true; // HEADER_GC_UNKNOWN_64
        case GC::CHAR_ADDITIONAL_INFO: info = { sizeof(TPacketGCCharAdditionalInfoBeavium), false }; return true;
        case 0x66: info = { 341, false }; return true; // HEADER_GC_MAIN_CHARACTER4_BGM_VOL
        case 0x67: info = { 25, false }; return true; // HEADER_GC_UNKNOWN_67
        case 0x68: info = { 80, false }; return true; // HEADER_GC_MOUNT_NAME
        case 0x69: info = { 3, true }; return true; // HEADER_GC_UNKNOWN_69
        case 0x6A: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_6A
        case 0x6B: info = { 32, false }; return true; // HEADER_GC_UNKNOWN_6B
        case GC::TARGET_HP: info = { sizeof(TPacketGCTargetHPBeavium), false }; return true;
        case 0x6D: info = { 6, false }; return true; // HEADER_GC_UNKNOWN_6D
        case 0x6E: info = { 37, false }; return true; // HEADER_GC_DRAGON_SOUL_REFINE
        case 0x70: info = { 51, false }; return true; // HEADER_GC_COMMAND_51
        case 0x71: info = { 101, false }; return true; // HEADER_GC_COMMAND_101
        case 0x72: info = { 257, false }; return true; // HEADER_GC_COMMAND_257
        case 0x73: info = { 513, false }; return true; // HEADER_GC_COMMAND_513
        case 0x75: info = { 1, false }; return true; // HEADER_GC_UNKNOWN_75
        case 0x76: info = { 133, false }; return true; // HEADER_GC_UNKNOWN_76
        case 0x77: info = { 5, false }; return true; // HEADER_GC_UNKNOWN_77
        case 0x78: info = { 4, true }; return true; // HEADER_GC_AUTH_SUCCESS
        case 0x79: info = { 281, false }; return true; // HEADER_GC_PANAMA
        case 0x7B: info = { 4, true }; return true; // HEADER_GC_HYBRIDCRYPT_SKEY
        case 0x7C: info = { 70, false }; return true; // HEADER_GC_OVERHEAD_TITLE
        case 0x7D: info = { 6, false }; return true; // HEADER_GC_UNKNOWN_7D
        case 0x7E: info = { 47, false }; return true; // HEADER_GC_UNKNOWN_7E
        case 0x7F: info = { 13, false }; return true; // HEADER_GC_UNKNOWN_7F
        case 0x80: info = { 13, false }; return true; // HEADER_GC_TARGET_STATE
        case 0x81: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_81
        case 0x82: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_82
        case 0x83: info = { 4, false }; return true; // HEADER_GC_UNKNOWN_83
        case 0x84: info = { 33, false }; return true; // HEADER_GC_CHAR_EFFECT_EXT
        case 0x85: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_85
        case 0x86: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_86
        case 0x87: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_87
        case 0x88: info = { 6, true }; return true; // HEADER_GC_DUNGEON_DATA
        case 0x89: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_89
        case 0x8A: info = { 51, false }; return true; // HEADER_GC_PET_INFO
        case 0x8B: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_8B
        case 0x8C: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_8C
        case 0x8D: info = { 170, false }; return true; // HEADER_GC_UNKNOWN_8D
        case 0x8E: info = { 1859, false }; return true; // HEADER_GC_UNKNOWN_8E
        case 0x8F: info = { 1859, false }; return true; // HEADER_GC_UNKNOWN_8F
        case 0x90: info = { 6, true }; return true; // HEADER_GC_VOICE_CHAT_DATA
        case 0x91: info = { 6, true }; return true; // HEADER_GC_UNKNOWN_91
        case 0x92: info = { 6635, false }; return true; // HEADER_GC_BLOCKED_PLAYERS_LIST
        case 0x93: info = { 35, false }; return true; // HEADER_GC_BLOCKED_PLAYER_MODIFY
        case 0x94: info = { 31, false }; return true; // HEADER_GC_UNKNOWN_94
        case 0x95: info = { 31, false }; return true; // HEADER_GC_UNKNOWN_95
        case 0x96: info = { 10, false }; return true; // HEADER_GC_AUTH_TOKEN
        case 0x97: info = { 8, false }; return true; // HEADER_GC_CASTING_PROGRESS
        case 0x9A: info = { 139, false }; return true; // HEADER_GC_SECURITY_CHALLENGE
        case 0xED: info = { 602, false }; return true; // HEADER_GC_AUTH_RSA_KEY
        case 0xFA: info = { 4, false }; return true; // HEADER_GC_KEY_AGREEMENT
        case 0xFB: info = { 137, false }; return true; // HEADER_GC_KEY_AGREEMENT_COMPLETED
        case 0xFC: info = { 5, false }; return true; // HEADER_GC_UNKNOWN_FC
        case GC::PHASE: info = { sizeof(TPacketGCPhaseBeavium), false }; return true;
        case GC::TIME_SYNC: info = { sizeof(TPacketGCHandshakeBeavium), false }; return true;
