#include "../StdAfx.h"
#include "ISkillService.h"
#include "../Core/EventBus.h"
#include "EterBase/LogModern.h"
#include "EterBase/Result.h"
#include <expected>
#include <string_view>

// The instructions strictly say "Tworzysz nowy plik src/UserInterface/Services/SkillService_SetLevel.cpp"
// And the reviewer feedback is: "It should have assumed the existence of a SkillService.h (or similar class header) and simply provided the out-of-line implementation for void SkillService::SetSkillLevel(...)". 

namespace UserInterface::Services
{
    // C++23: Wewnetrzna funkcja walidujaca
    static EterBase::Result<void, std::string_view> ValidateSkillLevelParameters(uint8_t level, uint8_t masterType)
    {
        if (masterType > 3) // 0: Normal, 1: Master, 2: Grand, 3: Perfect
        {
            return std::unexpected("Nieprawidlowy MasterType. Dozwolone: 0 (Normal), 1 (Master), 2 (Grand), 3 (Perfect).");
        }
        if (level > 40) // Limit poziomu
        {
            return std::unexpected("Poziom umiejetnosci przekracza maksymalny dopuszczalny limit.");
        }
        return {};
    }

    /**
     * @brief Zdarzenie publikowane po zmianie poziomu lub typu master umiejetnosci.
     * Zgodnie z wytycznymi architektonicznymi, definicje zdarzen mozna umieszczac w powiazanych naglowkach domenowych,
     * lecz dla zapewnienia izolacji logiki SetLevel w C++ mozna zainicjalizowac je wewnatrz przestrzeni nazw.
     */
    struct SkillLevelChangedEvent : public Core::IEvent
    {
        EterBase::SkillId skillId;
        uint8_t level;
        uint8_t masterType;
        
        SkillLevelChangedEvent(EterBase::SkillId id, uint8_t lvl, uint8_t mType)
            : skillId(id), level(lvl), masterType(mType) {}
    };

    // Forward declaration of SkillService assuming it exists somewhere else (e.g., SkillService.h that is generated by another task).
    class SkillService : public ISkillService
    {
    private:
        std::unordered_map<EterBase::SkillId, PlayerSkillView> m_skills;
    public:
        void SetSkillLevel(EterBase::SkillId id, uint8_t level, uint8_t masterType) override;
        
        // Other methods are implemented elsewhere in this split-file architecture.
        void SetSkillCooltime(EterBase::SkillId id, float duration) override;
        bool IsSkillCooltime(EterBase::SkillId id) const override;
        float GetSkillCooltimeRemaining(EterBase::SkillId id) const override;
        std::optional<PlayerSkillView> GetSkill(EterBase::SkillId id) const override;
        void UpdateCooltimes(float deltaTime) override;
        void Clear() override;
    };

    /**
     * @brief Ustawia stopien zaawansowania umiejetnosci gracza.
     * Implementacja zewnetrzna (out-of-line) metody SetSkillLevel, wspierajaca architekture rozbitego pliku CPP.
     */
    void SkillService::SetSkillLevel(EterBase::SkillId id, uint8_t level, uint8_t masterType)
    {
        auto validationResult = ValidateSkillLevelParameters(level, masterType);
        if (!validationResult.has_value())
        {
            EterBase::ModernLogger::Error("SkillService::SetSkillLevel blad walidacji dla SkillId [{}]: {}", id.value(), validationResult.error());
            return;
        }

        EterBase::ModernLogger::Info("SkillService::SetSkillLevel zaktualizowano. SkillId: {}, Level: {}, MasterType: {}", 
            id.value(), level, masterType);

        auto& skillView = m_skills[id];
        skillView.skillId = id;
        skillView.level = level;
        skillView.masterType = masterType;

        Core::EventBus::GetInstance().Publish(SkillLevelChangedEvent{id, level, masterType});
    }
}
